ITEM_KEY_TO_JAPANESE = {
    "main_risks_txt": "安静度・リスク",
    "main_contraindications_txt": "禁忌・特記事項",
    "adl_equipment_and_assistance_details_txt": "使用用具及び介助内容等",
    "goals_1_month_txt": "目標（1ヶ月）",
    "goals_at_discharge_txt": "目標（終了時）",
    "policy_treatment_txt": "治療方針",
    "policy_content_txt": "治療内容",
    "func_pain_txt": "疼痛",
    "func_rom_limitation_txt": "関節可動域制限",
    "func_muscle_weakness_txt": "筋力低下",
    "func_swallowing_disorder_txt": "摂食嚥下障害",
    "func_behavioral_psychiatric_disorder_txt": "精神行動障害",
    "func_nutritional_disorder_txt": "栄養障害",
    "func_excretory_disorder_txt": "排泄機能障害",
    "func_pressure_ulcer_txt": "褥瘡",
    "func_contracture_deformity_txt": "拘縮・変形",
    "func_motor_muscle_tone_abnormality_txt": "筋緊張異常",
    "func_disorientation_txt": "見当識障害",
    "func_memory_disorder_txt": "記憶障害",
    "goal_p_action_plan_txt": "参加の具体的な対応方針",
    "goal_a_action_plan_txt": "活動の具体的な対応方針",
    "goal_s_psychological_action_plan_txt": "心理の具体的な対応方針",
    "goal_s_env_action_plan_txt": "環境の具体的な対応方針",
    "goal_s_3rd_party_action_plan_txt": "第三者の不利に関する具体的な対応方針",
}

