from sqlalchemy import DECIMAL, TIMESTAMP, Boolean, Column, Date, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import relationship

from .base import Base


class RehabilitationPlan(Base):
    __tablename__ = "rehabilitation_plans"
    plan_id = Column(Integer, primary_key=True, autoincrement=True)
    patient_id = Column(Integer, ForeignKey("patients.patient_id"), nullable=False)
    created_by_staff_id = Column(Integer, ForeignKey("staff.id"))
    liked_items_json = Column(Text)
    created_at = Column(TIMESTAMP)

    patient = relationship("Patient", back_populates="plans")

    # schema.sql に基づく全カラム定義
    # 【1枚目】
    header_evaluation_date = Column(Date)
    header_disease_name_txt = Column(Text)
    header_treatment_details_txt = Column(Text)
    header_onset_date = Column(Date)
    header_rehab_start_date = Column(Date)
    header_therapy_pt_chk = Column(Boolean, default=False)
    header_therapy_ot_chk = Column(Boolean, default=False)
    header_therapy_st_chk = Column(Boolean, default=False)
    main_comorbidities_txt = Column(Text)
    main_risks_txt = Column(Text)
    main_contraindications_txt = Column(Text)
    func_consciousness_disorder_chk = Column(Boolean, default=False)
    func_consciousness_disorder_jcs_gcs_txt = Column(String(255))
    func_respiratory_disorder_chk = Column(Boolean, default=False)
    func_respiratory_o2_therapy_chk = Column(Boolean, default=False)
    func_respiratory_o2_therapy_l_min_txt = Column(String(255))
    func_respiratory_tracheostomy_chk = Column(Boolean, default=False)
    func_respiratory_ventilator_chk = Column(Boolean, default=False)
    func_circulatory_disorder_chk = Column(Boolean, default=False)
    func_circulatory_ef_chk = Column(Boolean, default=False)
    func_circulatory_ef_val = Column(Integer)
    func_circulatory_arrhythmia_chk = Column(Boolean, default=False)
    func_circulatory_arrhythmia_status_slct = Column(String(50))
    func_risk_factors_chk = Column(Boolean, default=False)
    func_risk_hypertension_chk = Column(Boolean, default=False)
    func_risk_dyslipidemia_chk = Column(Boolean, default=False)
    func_risk_diabetes_chk = Column(Boolean, default=False)
    func_risk_smoking_chk = Column(Boolean, default=False)
    func_risk_obesity_chk = Column(Boolean, default=False)
    func_risk_hyperuricemia_chk = Column(Boolean, default=False)
    func_risk_ckd_chk = Column(Boolean, default=False)
    func_risk_family_history_chk = Column(Boolean, default=False)
    func_risk_angina_chk = Column(Boolean, default=False)
    func_risk_omi_chk = Column(Boolean, default=False)
    func_risk_other_chk = Column(Boolean, default=False)
    func_risk_other_txt = Column(Text)
    func_swallowing_disorder_chk = Column(Boolean, default=False)
    func_swallowing_disorder_txt = Column(Text)
    func_nutritional_disorder_chk = Column(Boolean, default=False)
    func_nutritional_disorder_txt = Column(Text)
    func_excretory_disorder_chk = Column(Boolean, default=False)
    func_excretory_disorder_txt = Column(Text)
    func_pressure_ulcer_chk = Column(Boolean, default=False)
    func_pressure_ulcer_txt = Column(Text)
    func_pain_chk = Column(Boolean, default=False)
    func_pain_txt = Column(Text)
    func_other_chk = Column(Boolean, default=False)
    func_other_txt = Column(Text)
    func_rom_limitation_chk = Column(Boolean, default=False)
    func_rom_limitation_txt = Column(Text)
    func_contracture_deformity_chk = Column(Boolean, default=False)
    func_contracture_deformity_txt = Column(Text)
    func_muscle_weakness_chk = Column(Boolean, default=False)
    func_muscle_weakness_txt = Column(Text)
    func_motor_dysfunction_chk = Column(Boolean, default=False)
    func_motor_paralysis_chk = Column(Boolean, default=False)
    func_motor_involuntary_movement_chk = Column(Boolean, default=False)
    func_motor_ataxia_chk = Column(Boolean, default=False)
    func_motor_parkinsonism_chk = Column(Boolean, default=False)
    func_motor_muscle_tone_abnormality_chk = Column(Boolean, default=False)
    func_motor_muscle_tone_abnormality_txt = Column(Text)
    func_sensory_dysfunction_chk = Column(Boolean, default=False)
    func_sensory_hearing_chk = Column(Boolean, default=False)
    func_sensory_vision_chk = Column(Boolean, default=False)
    func_sensory_superficial_chk = Column(Boolean, default=False)
    func_sensory_deep_chk = Column(Boolean, default=False)
    func_speech_disorder_chk = Column(Boolean, default=False)
    func_speech_articulation_chk = Column(Boolean, default=False)
    func_speech_aphasia_chk = Column(Boolean, default=False)
    func_speech_stuttering_chk = Column(Boolean, default=False)
    func_speech_other_chk = Column(Boolean, default=False)
    func_speech_other_txt = Column(Text)
    func_higher_brain_dysfunction_chk = Column(Boolean, default=False)
    func_higher_brain_memory_chk = Column(Boolean, default=False)
    func_higher_brain_attention_chk = Column(Boolean, default=False)
    func_higher_brain_apraxia_chk = Column(Boolean, default=False)
    func_higher_brain_agnosia_chk = Column(Boolean, default=False)
    func_higher_brain_executive_chk = Column(Boolean, default=False)
    func_behavioral_psychiatric_disorder_chk = Column(Boolean, default=False)
    func_behavioral_psychiatric_disorder_txt = Column(Text)
    func_disorientation_chk = Column(Boolean, default=False)
    func_disorientation_txt = Column(Text)
    func_memory_disorder_chk = Column(Boolean, default=False)
    func_memory_disorder_txt = Column(Text)
    func_developmental_disorder_chk = Column(Boolean, default=False)
    func_developmental_asd_chk = Column(Boolean, default=False)
    func_developmental_ld_chk = Column(Boolean, default=False)
    func_developmental_adhd_chk = Column(Boolean, default=False)
    func_basic_rolling_chk = Column(Boolean, default=False)
    func_basic_rolling_independent_chk = Column(Boolean, default=False)
    func_basic_rolling_partial_assistance_chk = Column(Boolean, default=False)
    func_basic_rolling_assistance_chk = Column(Boolean, default=False)
    func_basic_rolling_not_performed_chk = Column(Boolean, default=False)
    func_basic_getting_up_chk = Column(Boolean, default=False)
    func_basic_getting_up_independent_chk = Column(Boolean, default=False)
    func_basic_getting_up_partial_assistance_chk = Column(Boolean, default=False)
    func_basic_getting_up_assistance_chk = Column(Boolean, default=False)
    func_basic_getting_up_not_performed_chk = Column(Boolean, default=False)
    func_basic_standing_up_chk = Column(Boolean, default=False)
    func_basic_standing_up_independent_chk = Column(Boolean, default=False)
    func_basic_standing_up_partial_assistance_chk = Column(Boolean, default=False)
    func_basic_standing_up_assistance_chk = Column(Boolean, default=False)
    func_basic_standing_up_not_performed_chk = Column(Boolean, default=False)
    func_basic_sitting_balance_chk = Column(Boolean, default=False)
    func_basic_sitting_balance_independent_chk = Column(Boolean, default=False)
    func_basic_sitting_balance_partial_assistance_chk = Column(Boolean, default=False)
    func_basic_sitting_balance_assistance_chk = Column(Boolean, default=False)
    func_basic_sitting_balance_not_performed_chk = Column(Boolean, default=False)
    func_basic_standing_balance_chk = Column(Boolean, default=False)
    func_basic_standing_balance_independent_chk = Column(Boolean, default=False)
    func_basic_standing_balance_partial_assistance_chk = Column(Boolean, default=False)
    func_basic_standing_balance_assistance_chk = Column(Boolean, default=False)
    func_basic_standing_balance_not_performed_chk = Column(Boolean, default=False)
    func_basic_other_chk = Column(Boolean, default=False)
    func_basic_other_txt = Column(Text)
    adl_eating_fim_start_val = Column(Integer)
    adl_eating_fim_current_val = Column(Integer)
    adl_eating_bi_start_val = Column(Integer)
    adl_eating_bi_current_val = Column(Integer)
    adl_grooming_fim_start_val = Column(Integer)
    adl_grooming_fim_current_val = Column(Integer)
    adl_grooming_bi_start_val = Column(Integer)
    adl_grooming_bi_current_val = Column(Integer)
    adl_bathing_fim_start_val = Column(Integer)
    adl_bathing_fim_current_val = Column(Integer)
    adl_bathing_bi_start_val = Column(Integer)
    adl_bathing_bi_current_val = Column(Integer)
    adl_dressing_upper_fim_start_val = Column(Integer)
    adl_dressing_upper_fim_current_val = Column(Integer)
    adl_dressing_lower_fim_start_val = Column(Integer)
    adl_dressing_lower_fim_current_val = Column(Integer)
    adl_dressing_bi_start_val = Column(Integer)
    adl_dressing_bi_current_val = Column(Integer)
    adl_toileting_fim_start_val = Column(Integer)
    adl_toileting_fim_current_val = Column(Integer)
    adl_toileting_bi_start_val = Column(Integer)
    adl_toileting_bi_current_val = Column(Integer)
    adl_bladder_management_fim_start_val = Column(Integer)
    adl_bladder_management_fim_current_val = Column(Integer)
    adl_bladder_management_bi_start_val = Column(Integer)
    adl_bladder_management_bi_current_val = Column(Integer)
    adl_bowel_management_fim_start_val = Column(Integer)
    adl_bowel_management_fim_current_val = Column(Integer)
    adl_bowel_management_bi_start_val = Column(Integer)
    adl_bowel_management_bi_current_val = Column(Integer)
    adl_transfer_bed_chair_wc_fim_start_val = Column(Integer)
    adl_transfer_bed_chair_wc_fim_current_val = Column(Integer)
    adl_transfer_toilet_fim_start_val = Column(Integer)
    adl_transfer_toilet_fim_current_val = Column(Integer)
    adl_transfer_tub_shower_fim_start_val = Column(Integer)
    adl_transfer_tub_shower_fim_current_val = Column(Integer)
    adl_transfer_bi_start_val = Column(Integer)
    adl_transfer_bi_current_val = Column(Integer)
    adl_locomotion_walk_walkingAids_wc_fim_start_val = Column(Integer)
    adl_locomotion_walk_walkingAids_wc_fim_current_val = Column(Integer)
    adl_locomotion_walk_walkingAids_wc_bi_start_val = Column(Integer)
    adl_locomotion_walk_walkingAids_wc_bi_current_val = Column(Integer)
    adl_locomotion_stairs_fim_start_val = Column(Integer)
    adl_locomotion_stairs_fim_current_val = Column(Integer)
    adl_locomotion_stairs_bi_start_val = Column(Integer)
    adl_locomotion_stairs_bi_current_val = Column(Integer)
    adl_comprehension_fim_start_val = Column(Integer)
    adl_comprehension_fim_current_val = Column(Integer)
    adl_expression_fim_start_val = Column(Integer)
    adl_expression_fim_current_val = Column(Integer)
    adl_social_interaction_fim_start_val = Column(Integer)
    adl_social_interaction_fim_current_val = Column(Integer)
    adl_problem_solving_fim_start_val = Column(Integer)
    adl_problem_solving_fim_current_val = Column(Integer)
    adl_memory_fim_start_val = Column(Integer)
    adl_memory_fim_current_val = Column(Integer)
    adl_equipment_and_assistance_details_txt = Column(Text)
    nutrition_height_chk = Column(Boolean, default=False)
    nutrition_height_val = Column(DECIMAL(5, 1))
    nutrition_weight_chk = Column(Boolean, default=False)
    nutrition_weight_val = Column(DECIMAL(5, 1))
    nutrition_bmi_chk = Column(Boolean, default=False)
    nutrition_bmi_val = Column(DECIMAL(4, 1))
    nutrition_method_oral_chk = Column(Boolean, default=False)
    nutrition_method_oral_meal_chk = Column(Boolean, default=False)
    nutrition_method_oral_supplement_chk = Column(Boolean, default=False)
    nutrition_method_tube_chk = Column(Boolean, default=False)
    nutrition_method_iv_chk = Column(Boolean, default=False)
    nutrition_method_iv_peripheral_chk = Column(Boolean, default=False)
    nutrition_method_iv_central_chk = Column(Boolean, default=False)
    nutrition_method_peg_chk = Column(Boolean, default=False)
    nutrition_swallowing_diet_slct = Column(String(50))
    nutrition_swallowing_diet_code_txt = Column(String(255))
    nutrition_status_assessment_slct = Column(String(50))
    nutrition_status_assessment_other_txt = Column(Text)
    nutrition_required_energy_val = Column(Integer)
    nutrition_required_protein_val = Column(Integer)
    nutrition_total_intake_energy_val = Column(Integer)
    nutrition_total_intake_protein_val = Column(Integer)
    social_care_level_status_chk = Column(Boolean, default=False)
    social_care_level_applying_chk = Column(Boolean, default=False)
    social_care_level_support_chk = Column(Boolean, default=False)
    social_care_level_support_num1_slct = Column(Boolean, default=False)
    social_care_level_support_num2_slct = Column(Boolean, default=False)
    social_care_level_care_slct = Column(Boolean, default=False)
    social_care_level_care_num1_slct = Column(Boolean, default=False)
    social_care_level_care_num2_slct = Column(Boolean, default=False)
    social_care_level_care_num3_slct = Column(Boolean, default=False)
    social_care_level_care_num4_slct = Column(Boolean, default=False)
    social_care_level_care_num5_slct = Column(Boolean, default=False)
    social_disability_certificate_physical_chk = Column(Boolean, default=False)
    social_disability_certificate_physical_txt = Column(Text)
    social_disability_certificate_physical_type_txt = Column(String(255))
    social_disability_certificate_physical_rank_val = Column(Integer)
    social_disability_certificate_mental_chk = Column(Boolean, default=False)
    social_disability_certificate_mental_rank_val = Column(Integer)
    social_disability_certificate_intellectual_chk = Column(Boolean, default=False)
    social_disability_certificate_intellectual_txt = Column(Text)
    social_disability_certificate_intellectual_grade_txt = Column(String(255))
    social_disability_certificate_other_chk = Column(Boolean, default=False)
    social_disability_certificate_other_txt = Column(Text)
    goals_1_month_txt = Column(Text)
    goals_at_discharge_txt = Column(Text)
    goals_planned_hospitalization_period_chk = Column(Boolean, default=False)
    goals_planned_hospitalization_period_txt = Column(Text)
    goals_discharge_destination_chk = Column(Boolean, default=False)
    goals_discharge_destination_txt = Column(Text)
    goals_long_term_care_needed_chk = Column(Boolean, default=False)
    policy_treatment_txt = Column(Text)
    policy_content_txt = Column(Text)
    signature_rehab_doctor_txt = Column(String(255))
    signature_primary_doctor_txt = Column(String(255))
    signature_pt_txt = Column(String(255))
    signature_ot_txt = Column(String(255))
    signature_st_txt = Column(String(255))
    signature_nurse_txt = Column(String(255))
    signature_dietitian_txt = Column(String(255))
    signature_social_worker_txt = Column(String(255))
    signature_explained_to_txt = Column(String(255))
    signature_explanation_date = Column(Date)
    signature_explainer_txt = Column(String(255))

    # 【2枚目】
    goal_p_residence_chk = Column(Boolean, default=False)
    goal_p_residence_slct = Column(String(50))
    goal_p_residence_other_txt = Column(Text)
    goal_p_return_to_work_chk = Column(Boolean, default=False)
    goal_p_return_to_work_status_slct = Column(String(50))
    goal_p_return_to_work_status_other_txt = Column(Text)
    goal_p_return_to_work_commute_change_chk = Column(Boolean, default=False)
    goal_p_schooling_chk = Column(Boolean, default=False)
    goal_p_schooling_status_possible_chk = Column(Boolean, default=False)
    goal_p_schooling_status_needs_consideration_chk = Column(Boolean, default=False)
    goal_p_schooling_status_change_course_chk = Column(Boolean, default=False)
    goal_p_schooling_status_not_possible_chk = Column(Boolean, default=False)
    goal_p_schooling_status_other_chk = Column(Boolean, default=False)
    goal_p_schooling_status_other_txt = Column(Text)
    goal_p_schooling_destination_chk = Column(Boolean, default=False)
    goal_p_schooling_destination_txt = Column(Text)
    goal_p_schooling_commute_change_chk = Column(Boolean, default=False)
    goal_p_schooling_commute_change_txt = Column(Text)
    goal_p_household_role_chk = Column(Boolean, default=False)
    goal_p_household_role_txt = Column(Text)
    goal_p_social_activity_chk = Column(Boolean, default=False)
    goal_p_social_activity_txt = Column(Text)
    goal_p_hobby_chk = Column(Boolean, default=False)
    goal_p_hobby_txt = Column(Text)
    goal_a_bed_mobility_chk = Column(Boolean, default=False)
    goal_a_bed_mobility_independent_chk = Column(Boolean, default=False)
    goal_a_bed_mobility_assistance_chk = Column(Boolean, default=False)
    goal_a_bed_mobility_not_performed_chk = Column(Boolean, default=False)
    goal_a_bed_mobility_equipment_chk = Column(Boolean, default=False)
    goal_a_bed_mobility_environment_setup_chk = Column(Boolean, default=False)
    goal_a_indoor_mobility_chk = Column(Boolean, default=False)
    goal_a_indoor_mobility_independent_chk = Column(Boolean, default=False)
    goal_a_indoor_mobility_assistance_chk = Column(Boolean, default=False)
    goal_a_indoor_mobility_not_performed_chk = Column(Boolean, default=False)
    goal_a_indoor_mobility_equipment_chk = Column(Boolean, default=False)
    goal_a_indoor_mobility_equipment_txt = Column(Text)
    goal_a_outdoor_mobility_chk = Column(Boolean, default=False)
    goal_a_outdoor_mobility_independent_chk = Column(Boolean, default=False)
    goal_a_outdoor_mobility_assistance_chk = Column(Boolean, default=False)
    goal_a_outdoor_mobility_not_performed_chk = Column(Boolean, default=False)
    goal_a_outdoor_mobility_equipment_chk = Column(Boolean, default=False)
    goal_a_outdoor_mobility_equipment_txt = Column(Text)
    goal_a_driving_chk = Column(Boolean, default=False)
    goal_a_driving_independent_chk = Column(Boolean, default=False)
    goal_a_driving_assistance_chk = Column(Boolean, default=False)
    goal_a_driving_not_performed_chk = Column(Boolean, default=False)
    goal_a_driving_modification_chk = Column(Boolean, default=False)
    goal_a_driving_modification_txt = Column(Text)
    goal_a_public_transport_chk = Column(Boolean, default=False)
    goal_a_public_transport_independent_chk = Column(Boolean, default=False)
    goal_a_public_transport_assistance_chk = Column(Boolean, default=False)
    goal_a_public_transport_not_performed_chk = Column(Boolean, default=False)
    goal_a_public_transport_type_chk = Column(Boolean, default=False)
    goal_a_public_transport_type_txt = Column(Text)
    goal_a_toileting_chk = Column(Boolean, default=False)
    goal_a_toileting_independent_chk = Column(Boolean, default=False)
    goal_a_toileting_assistance_chk = Column(Boolean, default=False)
    goal_a_toileting_assistance_clothing_chk = Column(Boolean, default=False)
    goal_a_toileting_assistance_wiping_chk = Column(Boolean, default=False)
    goal_a_toileting_assistance_catheter_chk = Column(Boolean, default=False)
    goal_a_toileting_type_chk = Column(Boolean, default=False)
    goal_a_toileting_type_western_chk = Column(Boolean, default=False)
    goal_a_toileting_type_japanese_chk = Column(Boolean, default=False)
    goal_a_toileting_type_other_chk = Column(Boolean, default=False)
    goal_a_toileting_type_other_txt = Column(Text)
    goal_a_eating_chk = Column(Boolean, default=False)
    goal_a_eating_independent_chk = Column(Boolean, default=False)
    goal_a_eating_assistance_chk = Column(Boolean, default=False)
    goal_a_eating_not_performed_chk = Column(Boolean, default=False)
    goal_a_eating_method_chopsticks_chk = Column(Boolean, default=False)
    goal_a_eating_method_fork_etc_chk = Column(Boolean, default=False)
    goal_a_eating_method_tube_feeding_chk = Column(Boolean, default=False)
    goal_a_eating_diet_form_txt = Column(Text)
    goal_a_grooming_chk = Column(Boolean, default=False)
    goal_a_grooming_independent_chk = Column(Boolean, default=False)
    goal_a_grooming_assistance_chk = Column(Boolean, default=False)
    goal_a_dressing_chk = Column(Boolean, default=False)
    goal_a_dressing_independent_chk = Column(Boolean, default=False)
    goal_a_dressing_assistance_chk = Column(Boolean, default=False)
    goal_a_bathing_chk = Column(Boolean, default=False)
    goal_a_bathing_independent_chk = Column(Boolean, default=False)
    goal_a_bathing_assistance_chk = Column(Boolean, default=False)
    goal_a_bathing_type_tub_chk = Column(Boolean, default=False)
    goal_a_bathing_type_shower_chk = Column(Boolean, default=False)
    goal_a_bathing_assistance_body_washing_chk = Column(Boolean, default=False)
    goal_a_bathing_assistance_transfer_chk = Column(Boolean, default=False)
    goal_a_housework_meal_chk = Column(Boolean, default=False)
    goal_a_housework_meal_all_chk = Column(Boolean, default=False)
    goal_a_housework_meal_not_performed_chk = Column(Boolean, default=False)
    goal_a_housework_meal_partial_chk = Column(Boolean, default=False)
    goal_a_housework_meal_partial_txt = Column(Text)
    goal_a_writing_chk = Column(Boolean, default=False)
    goal_a_writing_independent_chk = Column(Boolean, default=False)
    goal_a_writing_independent_after_hand_change_chk = Column(Boolean, default=False)
    goal_a_writing_other_chk = Column(Boolean, default=False)
    goal_a_writing_other_txt = Column(Text)
    goal_a_ict_chk = Column(Boolean, default=False)
    goal_a_ict_independent_chk = Column(Boolean, default=False)
    goal_a_ict_assistance_chk = Column(Boolean, default=False)
    goal_a_communication_chk = Column(Boolean, default=False)
    goal_a_communication_independent_chk = Column(Boolean, default=False)
    goal_a_communication_assistance_chk = Column(Boolean, default=False)
    goal_a_communication_device_chk = Column(Boolean, default=False)
    goal_a_communication_letter_board_chk = Column(Boolean, default=False)
    goal_a_communication_cooperation_chk = Column(Boolean, default=False)
    goal_s_psychological_support_chk = Column(Boolean, default=False)
    goal_s_psychological_support_txt = Column(Text)
    goal_s_disability_acceptance_chk = Column(Boolean, default=False)
    goal_s_disability_acceptance_txt = Column(Text)
    goal_s_psychological_other_chk = Column(Boolean, default=False)
    goal_s_psychological_other_txt = Column(Text)
    goal_s_env_home_modification_chk = Column(Boolean, default=False)
    goal_s_env_home_modification_txt = Column(Text)
    goal_s_env_assistive_device_chk = Column(Boolean, default=False)
    goal_s_env_assistive_device_txt = Column(Text)
    goal_s_env_social_security_chk = Column(Boolean, default=False)
    goal_s_env_social_security_physical_disability_cert_chk = Column(Boolean, default=False)
    goal_s_env_social_security_disability_pension_chk = Column(Boolean, default=False)
    goal_s_env_social_security_intractable_disease_cert_chk = Column(Boolean, default=False)
    goal_s_env_social_security_other_chk = Column(Boolean, default=False)
    goal_s_env_social_security_other_txt = Column(Text)
    goal_s_env_care_insurance_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_details_txt = Column(Text)
    goal_s_env_care_insurance_outpatient_rehab_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_home_rehab_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_day_care_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_home_nursing_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_home_care_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_health_facility_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_nursing_home_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_care_hospital_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_other_chk = Column(Boolean, default=False)
    goal_s_env_care_insurance_other_txt = Column(Text)
    goal_s_env_disability_welfare_chk = Column(Boolean, default=False)
    goal_s_env_disability_welfare_after_school_day_service_chk = Column(Boolean, default=False)
    goal_s_env_disability_welfare_child_development_support_chk = Column(Boolean, default=False)
    goal_s_env_disability_welfare_life_care_chk = Column(Boolean, default=False)
    goal_s_env_disability_welfare_other_chk = Column(Boolean, default=False)
    goal_s_env_other_chk = Column(Boolean, default=False)
    goal_s_env_other_txt = Column(Text)
    goal_s_3rd_party_main_caregiver_chk = Column(Boolean, default=False)
    goal_s_3rd_party_main_caregiver_txt = Column(Text)
    goal_s_3rd_party_family_structure_change_chk = Column(Boolean, default=False)
    goal_s_3rd_party_family_structure_change_txt = Column(Text)
    goal_s_3rd_party_household_role_change_chk = Column(Boolean, default=False)
    goal_s_3rd_party_household_role_change_txt = Column(Text)
    goal_s_3rd_party_family_activity_change_chk = Column(Boolean, default=False)
    goal_s_3rd_party_family_activity_change_txt = Column(Text)
    goal_p_action_plan_txt = Column(Text)
    goal_a_action_plan_txt = Column(Text)
    goal_s_psychological_action_plan_txt = Column(Text)
    goal_s_env_action_plan_txt = Column(Text)
    goal_s_3rd_party_action_plan_txt = Column(Text)


class SuggestionLike(Base):
    __tablename__ = "suggestion_likes"
    patient_id = Column(Integer, ForeignKey("patients.patient_id"), primary_key=True, nullable=False)
    item_key = Column(String(255), primary_key=True, nullable=False)  # 複合主キーの一部
    liked_model = Column(String(50), primary_key=True, nullable=False)  # 主キーに追加し、NULLを許可しない
    staff_id = Column(Integer, ForeignKey("staff.id"), nullable=False)  # 誰がいいねしたかを記録
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())
    updated_at = Column(TIMESTAMP, nullable=False, server_default=func.now(), onupdate=func.now())

    # Relationships
    patient = relationship("Patient", back_populates="suggestion_likes")
    staff = relationship("Staff", back_populates="suggestion_likes")


class LikedItemDetail(Base):
    __tablename__ = "liked_item_details"
    id = Column(Integer, primary_key=True, autoincrement=True)
    rehabilitation_plan_id = Column(Integer, ForeignKey("rehabilitation_plans.plan_id"), nullable=False)
    staff_id = Column(Integer, ForeignKey("staff.id"), nullable=False)
    item_key = Column(String(255), nullable=False)
    liked_model = Column(Text, nullable=True)
    general_suggestion_text = Column(Text)
    specialized_suggestion_text = Column(Text)
    therapist_notes_at_creation = Column(Text)
    patient_info_snapshot_json = Column(Text)  # JSON型がないMySQLバージョンも考慮しTextで
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())

    # Relationships
    plan = relationship("RehabilitationPlan")
    staff = relationship("Staff")


class RegenerationHistory(Base):
    __tablename__ = "regeneration_history"
    id = Column(Integer, primary_key=True, autoincrement=True)
    rehabilitation_plan_id = Column(Integer, ForeignKey("rehabilitation_plans.plan_id"), nullable=False)
    item_key = Column(String(255), nullable=False)
    model_type = Column(String(50), nullable=False)
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())

    plan = relationship("RehabilitationPlan")
